#!/usr/bin/env python3
"""Generate Priorities.lua from a "TBC Loot Prio" CSV export.

Usage: build_priorities.py <input_file>

Each item row (identified by a wowhead item link, .../tbc/item={iid}/...)
becomes an entry `[iid] = { {class, ...}, {class, ...}, ... }` keyed on the
item id, where each inner list is one priority tier.

If Priorities.lua already exists next to the output location, it is parsed
and merged with the newly-generated entries: entries for item ids present in
the CSV overwrite the existing ones, while item ids only present in the
existing file are kept unchanged.
"""

import csv
import re
import sys
from pathlib import Path

OUTPUT_FILENAME = "Priorities.lua"
COMMENT_COL = 7
MAX_COMMENT_LENGTH = 255
ITEM_LINK_RE = re.compile(r"/tbc/item=(\d+)")
EXISTING_ENTRY_RE = re.compile(r"^\[(\d+)\]\s*=\s*(\{.*\})\s*,?\s*$")


def lua_string(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def parse_priority_cell(cell):
    classes = [c.strip() for c in cell.split(",")]
    return [c for c in classes if c]


def format_entry(tiers, comment):
    tier_strs = ["{ " + ", ".join(lua_string(c) for c in tier) + " }" for tier in tiers]
    parts = ", ".join(tier_strs)
    if comment:
        parts += ", comment = " + lua_string(comment)
    return "{ " + parts + " }"


def parse_csv(input_path):
    entries = {}
    with open(input_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.reader(f)
        next(reader, None)  # header row
        for row in reader:
            if len(row) < 2:
                continue
            match = ITEM_LINK_RE.search(row[1])
            if not match:
                continue
            iid = int(match.group(1))
            tiers = []
            for cell in row[2:7]:
                tier = parse_priority_cell(cell)
                if tier:
                    tiers.append(tier)
            comment = row[COMMENT_COL].strip() if len(row) > COMMENT_COL else ""
            if comment and len(comment) > MAX_COMMENT_LENGTH:
                raise ValueError(
                    f"Comment for item {iid} is {len(comment)} characters, "
                    f"exceeding the {MAX_COMMENT_LENGTH} limit"
                )
            entries[iid] = (tiers, comment or None)
    return entries


def parse_existing_lua(output_path):
    entries = {}
    if not output_path.exists():
        return entries
    with open(output_path, encoding="utf-8") as f:
        for line in f:
            match = EXISTING_ENTRY_RE.match(line.strip())
            if match:
                entries[int(match.group(1))] = match.group(2)
    return entries


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <input_file>", file=sys.stderr)
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = Path(OUTPUT_FILENAME)

    new_entries = parse_csv(input_path)
    merged = parse_existing_lua(output_path)
    for iid, (tiers, comment) in new_entries.items():
        merged[iid] = format_entry(tiers, comment)

    lines = [
        "-- Auto-generated by build_priorities.py. Do not edit manually.",
        "local addonName, addon = ...",
        "",
        "addon.Priorities = {",
    ]
    for iid in sorted(merged):
        lines.append(f"\t[{iid}] = {merged[iid]},")
    lines.append("}")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(merged)} entries ({len(new_entries)} from CSV) to {output_path}")


if __name__ == "__main__":
    main()
